import { CheckCircle2, Sparkles } from "lucide-react";

function ListCard({ title, items }) {
  return <article className="rounded-2xl border border-white/10 bg-[#0F172A]/70 p-5"><h3 className="text-sm font-semibold uppercase tracking-[0.14em] text-violet-200">{title}</h3>{items.length ? <ul className="mt-3 space-y-3">{items.map((item, index) => <li key={`${item}-${index}`} className="flex gap-3 text-sm leading-7 text-slate-300"><CheckCircle2 className="mt-1 size-4 shrink-0 text-emerald-300" />{item}</li>)}</ul> : <p className="mt-3 text-sm leading-7 text-slate-400">No specific guidance applies here.</p>}</article>;
}

export default function MentorReport({ answer }) {
  return <section aria-labelledby="mentor-report-heading" className="rounded-[28px] border border-white/10 bg-white/[0.04] p-5 shadow-[0_20px_80px_rgba(0,0,0,0.25)] backdrop-blur-xl sm:p-6"><div><span className="inline-flex items-center gap-2 rounded-full bg-violet-400/15 px-3 py-1 text-xs font-semibold text-violet-100 ring-1 ring-violet-400/25"><Sparkles className="size-3.5" />AI Analysis</span><h2 id="mentor-report-heading" className="mt-3 text-xl font-semibold text-white">{answer.topic}</h2><p className="mt-2 text-sm leading-7 text-slate-300">{answer.summary}</p></div><div className="mt-6 grid gap-4 md:grid-cols-2"><article className="rounded-2xl border border-white/10 bg-[#0F172A]/70 p-5 md:col-span-2"><h3 className="text-sm font-semibold uppercase tracking-[0.14em] text-violet-200">Why it matters</h3><p className="mt-3 text-sm leading-7 text-slate-300">{answer.whyItMatters}</p></article><ListCard title="What is wrong" items={answer.whatIsWrong} /><ListCard title="Best practices" items={answer.bestPractices} /><ListCard title="Better approach" items={answer.betterApproach} /><article className="rounded-2xl border border-white/10 bg-[#0F172A]/70 p-5"><h3 className="text-sm font-semibold uppercase tracking-[0.14em] text-violet-200">Example code</h3><pre className="mt-3 overflow-x-auto rounded-xl bg-slate-950/80 p-4 text-sm leading-6 text-cyan-100"><code>{answer.exampleCode}</code></pre></article><ListCard title="Learning tips" items={answer.learningTips} /><ListCard title="Next steps" items={answer.nextSteps} /></div></section>;
}
