import { Code2 } from "lucide-react";
import { useState } from "react";
import DashboardLayout from "../components/dashboard/DashboardLayout";
import CodeReviewReport from "../components/reports/CodeReviewReport";
import ErrorMessage from "../components/reports/ErrorMessage";
import LoadingState from "../components/reports/LoadingState";
import PageHeader from "../components/reports/PageHeader";
import EmptyState from "../components/reports/EmptyState";
import { reviewCode } from "../services/api";
import { saveReviewHistory } from "../services/reviewHistory";

export default function CodeReview() {
  const [language, setLanguage] = useState("javascript"); const [code, setCode] = useState(""); const [report, setReport] = useState(null); const [error, setError] = useState(""); const [loading, setLoading] = useState(false);
  async function submitReview() { if (!code.trim()) { setError("Add code before starting a review."); return; } if (code.trim().length > 20000) { setError("Code must not exceed 20000 characters."); return; } setError(""); setLoading(true); setReport(null); try { const { data } = await reviewCode(language, code); saveReviewHistory({ type: "code", title: `${language[0].toUpperCase()}${language.slice(1)} Code Review`, summary: data.summary || "Code review completed.", score: data.overallScore, route: "/code-review", metadata: { language } }); setReport(data); } catch (requestError) { setError(requestError.response?.data?.error || "We could not create the code review. Confirm the backend is running and retry."); } finally { setLoading(false); } }
  function handleSubmit(event) { event.preventDefault(); submitReview(); }
  return <DashboardLayout title="Code Review"><div className="space-y-8"><PageHeader eyebrow="Code intelligence" title="Review code with confidence" description="Assess quality, maintainability, security, and practical best practices with an AI code review." />
    <form onSubmit={handleSubmit} className="rounded-[28px] border border-white/10 bg-white/[0.04] p-5 shadow-[0_20px_80px_rgba(0,0,0,0.25)] backdrop-blur-xl sm:p-6"><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><label htmlFor="language" className="text-sm font-semibold text-white">Language</label><select id="language" value={language} onChange={(event) => setLanguage(event.target.value)} className="mt-2 block rounded-xl border border-white/10 bg-[#0F172A] px-4 py-3 text-sm text-white outline-none focus:border-violet-400/60"><option value="html">HTML</option><option value="css">CSS</option><option value="javascript">JavaScript</option></select></div><button disabled={loading} className="inline-flex items-center justify-center gap-2 rounded-xl bg-gradient-to-r from-violet-500 to-indigo-500 px-5 py-3.5 font-semibold text-white transition hover:from-violet-400 hover:to-indigo-400 disabled:cursor-not-allowed disabled:opacity-60"><Code2 size={18} />{loading ? "Analyzing…" : "Analyze Code"}</button></div><label htmlFor="code" className="mt-5 block text-sm font-semibold text-white">Code to review</label><textarea id="code" value={code} onChange={(event) => setCode(event.target.value)} placeholder="Paste your HTML, CSS, or JavaScript here..." className="mt-3 min-h-72 w-full resize-y rounded-2xl border border-white/10 bg-[#0F172A]/80 p-4 font-mono text-sm leading-6 text-slate-200 outline-none transition placeholder:text-slate-600 focus:border-violet-400/60 focus:ring-2 focus:ring-violet-400/15" /><p className="mt-2 text-right text-xs text-slate-500">{code.trim().length}/20000 characters</p></form>
    <ErrorMessage message={error} />{error && code.trim() && <button type="button" onClick={submitReview} disabled={loading} className="rounded-xl border border-violet-400/30 px-4 py-2 text-sm font-semibold text-violet-100 transition hover:bg-violet-400/10 disabled:cursor-not-allowed disabled:opacity-60">Retry analysis</button>}{loading && <LoadingState label="Reviewing code" />}{!loading && !report && !error && <EmptyState title="Turn code into clear next steps" description="Paste HTML, CSS, or JavaScript to assess quality, maintainability, security, performance, and best practices." />}{report && <CodeReviewReport report={report} />}</div></DashboardLayout>;
}
